### ISSUE TITLE
error: can't open keyboard device input file

### ISSUE THREAD

**Issue by uniume** [inwskatsube/oyainput#12]
fedora 27、ibus + mozc、キーボードの接続は１個の環境です。

> error: Failed to open keyboard device event file! %s: No such file or directory
にて起動しませんでした。

printfで変数を確認したところ、
> devcnt is 1 
> usedevno is -1 
> devpath is /dev/input/event 
でした。

複数キーボードの判別をコメントアウトして、
強制的にusedevno=0とすると、
> devcnt is 1 
> usedevno is 0 
> devpath is /dev/input/event4 
となり、エラーなく使えております。

**Comment by inwskatsube** [comment]
ありがとうございます。別の場所でもご指摘頂いて気づきました。
修正いたしました。
