### ISSUE TITLE
oyainputを起動すると、キーボードが使えなくなる

### ISSUE THREAD

**Issue by tsubota-kouga** [inwskatsube/oyainput#17]
以前は通常通り使えていたのですが、アップデートをした際にoyainputを起動するとキーボードが使えなくなる現象が起きました。

色々調べてみたところ、
`oyainput.c`の166行目の`KEY_MAX`のところがなぜかうまく行っていないようで、
`KEY_MAX`を`0x240`に置き換えるとうまく起動することが分かりました。

(同じ現象に遭遇した方の参考になれば...)

同じ現象に遭遇した方はいますでしょうか?

環境
- Ubuntu 22.04
- Linux Kernel 5.15.0-40-generic

**Comment by takkifjmt** [comment]
Ubuntu22.04にしたところ同様の現象が発生しました。解決方法をご教示いただき
大変助かりました。ありがとうございます。

**Comment by kazu202104** [comment]
同じく頭痛めてたところで、救われました。Thank you veeery much!!

**Comment by inwskatsube** [comment]
@tsubota-kouga 
調べていただきありがとうございます！
ソースに反映いたしました。

**Comment by tsubota-kouga** [comment]
反映ありがとうございます
この変更で環境が壊れた方がいれば、またopenしてもらえばいいので一旦closeしますね
